project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project"
  site-url: "https://rachelren-rsh.github.io/550-final-quarto-website/" 
  repo-url: https://github.com/RachelRen-RSH/550-final-quarto-website 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Sihan Ren, 2023"

  sidebar:
    logo: "images/Miami_beach_1.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://catalog.upenn.edu/graduate/programs/urban-spatial-analytics-musa/
        text: "MUSA Website"         

    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Introduction
      - href: Methods.qmd
        text: Methods
      - section: Results
        contents:
          - analysis/Data Visualizations.ipynb
          - analysis/Regression Analysis.ipynb
      - href: Limitations.qmd
        text: Limitations
      - href: References.qmd
        text: References

format:
  html:
    highlight-style: solarized
    theme: Superhero
    fontsize: 14pt
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




