---
title: "Hotels' Christmas Holiday Price Prediction in Miami, FL"
subtitle: "MUSA 550 Final Project by Jingyi Li, Sihan Ren, Sijia Zhang"
---

## Overview
Miami, Florida, a popular destination for Christmas and New Year's celebrations, is famous for its pleasant climate and vibrant atmosphere. To enhance the experience of visitors to this tropical paradise, our team created an application to help tourists eliminate worries about choosing hotels, which can both save money and time. It is not only a travel companion, but also it's a smart, personalized guide to ensuring a joyful and stress-free holiday experience in Miami's festive ambiance.

Our application offers two unique and attractive features. Firstly, we provide an in-depth analysis of the correlations between hotel holiday prices in 2023 and various factors such as their ratings, amenities, and the surrounding environment or demographics in Miami. This allows visitors to understand what influences the cost of their stay and whether there are some outliers that the price do not relates with the adjacent environment and amenities to help them make informed decisions. Secondly, our application creates a machine learning model with random forest regression to predict hotel holiday prices.  







 
